---
- hosts: all

  tasks:
    - name: pip | pyenv | tools3 | install requirements using shell
      tags: pip,pyenv,tools3
      shell: |
        # cd to project directory
        ~/.pyenv/versions/tools3/bin/python -m pip install -U ansible colorama cookiecutter gnucash-to-beancount mps-youtube rows speedtest-cli fast.com zabbix-api youtube-dl tmuxp
        if [ ! -L ~/bin/pytest]; then
          ln -s ~/.pyenv/versions/tools3/bin/pytest ~/bin/pytest
        fi
        if [ ! -L ~/bin/tmuxp]; then
          ln -s ~/.pyenv/versions/tools3/bin/tmuxp ~/bin/tmuxp
        fi
      args:
        executable: /bin/bash
      register: pip_tools3_script_result

    - name: pip | pyenv | jupyter3 | install requirements using shell
      tags: pip,pyenv,jupyter3
      shell: |
        # cd to project directory
        ~/.pyenv/versions/jupyter3/bin/python -m pip install -U jupyter environment_kernels
        ~/.pyenv/versions/jupyter3/bin/python -m ipykernel install --user
        ~/.pyenv/versions/jupyter3/bin/jupyter notebook --generate-config
        if [ ! -L ~/bin/jupyter]; then
          ln -s ~/.pyenv/versions/jupyter3/bin/jupyter ~/bin/jupyter
        fi
      args:
        executable: /bin/bash
      register: pip_jupyter3_script_result

    - name: pip | pyenv | tools2 | install requirements using shell
      tags: pip,pyenv,tools2
      shell: |
        # cd to project directory
        ~/.pyenv/versions/tools2/bin/python -m pip install -U rename s3cmd fabric mercurial pip
      args:
        executable: /bin/bash
      register: pip_tools2_script_result

    - name: pip | pyenv | neovim2 | install requirements using shell
      tags: pip,pyenv,neovim2
      shell: |
        # cd to project directory
        ~/.pyenv/versions/neovim2/bin/python -m pip install -U pip pynvim
      args:
        executable: /bin/bash
      register: pip_neovim2_script_result

    - name: pip | pyenv | neovim3 | install requirements using shell
      tags: pip,pyenv,neovim3
      shell: |
        # cd to project directory
        ~/.pyenv/versions/neovim3/bin/python -m pip install -U pip black pynvim pylint flake8 jedi autopep8 pep8 pydocstyle pyflakes isort yapf yamllint mypy
        if [ ! -L ~/bin/autopep8]; then
          ln -s `pyenv which autopep8` ~/bin/autopep8
        fi
        if [ ! -L ~/bin/black]; then
          ln -s `pyenv which black` ~/bin/black
        fi
        if [ ! -L ~/bin/flake8]; then
          ln -s `pyenv which flake8` ~/bin/flake8
        fi
        if [ ! -L ~/bin/isort]; then
          ln -s `pyenv which isort` ~/bin/isort
        fi
        if [ ! -L ~/bin/jedi]; then
          ln -s `pyenv which jedi` ~/bin/jedi
        fi
        if [ ! -L ~/bin/mypy]; then
          ln -s `pyenv which mypy` ~/bin/mypy
        fi
        if [ ! -L ~/bin/pydocstyle]; then
          ln -s `pyenv which pydocstyle` ~/bin/pydocstyle
        fi
        if [ ! -L ~/bin/pylint]; then
          ln -s `pyenv which pylint` ~/bin/pylint
        fi
        if [ ! -L ~/bin/yapf]; then
          ln -s `pyenv which yapf` ~/bin/yapf
        fi
        if [ ! -L ~/bin/yamllint]; then
          ln -s `pyenv which yamllint` ~/bin/yamllint
        fi
      args:
        executable: /bin/bash
      register: pip_neovim3_script_result

    - name: pip | ipython | configuration
      tags: pip,pyenv,ipython
      shell: |
        # cd to project directory
        ipython profile create
        curl -L http://hbn.link/hb-ipython-startup-script > ~/.ipython/profile_default/startup/00-venv-sitepackages.py
      args:
        executable: /bin/bash
