---
- hosts: all

  tasks:
    - name: pip | pyenv | tools3 | install requirements using shell
      tags: packages,pyenv,workstation-packages,pip,tools3
      shell: |
        # cd to project directory
        ~/.pyenv/versions/tools3/bin/python -m pip install -U ansible colorama cookiecutter gnucash-to-beancount mps-youtube rows speedtest-cli fast.com zabbix-api youtube-dl tmuxp
      args:
        executable: /bin/bash
      register: pip_tools3_script_result

    - name: pip | pyenv | tools3 | link pytest
      tags: packages,pyenv,workstation-packages,pip,tools3,pytest-link
      file:
        src: ~/.pyenv/versions/tools3/bin/pytest
        dest: ~/bin/pytest
        owner: barbosa
        group: barbosa
        state: link

    - name: pip | pyenv | tools3 | link tmuxp
      tags: packages,pyenv,workstation-packages,pip,tools3,tmuxp-link
      file:
        src: ~/.pyenv/versions/tools3/bin/tmuxp
        dest: ~/bin/tmuxp
        owner: barbosa
        group: barbosa
        state: link

    # - name: pip | pyenv | jupyter3 | install requirements using shell
    #   shell: |
    #     # cd to project directory
    #     ~/.pyenv/versions/jupyter3/bin/python -m pip install -U jupyter environment_kernels
    #     ~/.pyenv/versions/jupyter3/bin/python -m ipykernel install --user
    #     ~/.pyenv/versions/jupyter3/bin/jupyter notebook --generate-config -y
    #     executable: /bin/bash
    #   register: pip_jupyter3_script_result

    - name: pip | pyenv | jupyter3 | link jupyter
      tags: packages,pyenv,workstation-packages,pip,jupyter3,jupyter3-link
      file:
        src: ~/.pyenv/versions/jupyter3/bin/jupyter
        dest: ~/bin/jupyter
        owner: barbosa
        group: barbosa
        state: link

    - name: pip | pyenv | tools2 | install requirements using shell
      tags: packages,pyenv,workstation-packages,pip,tools2
      shell: |
        # cd to project directory
        ~/.pyenv/versions/tools2/bin/python -m pip install -U rename s3cmd fabric mercurial pip
      args:
        executable: /bin/bash
      register: pip_tools2_script_result

    - name: pip | pyenv | neovim2 | install requirements using shell
      tags: packages,pyenv,workstation-packages,pip,neovim2
      shell: |
        # cd to project directory
        ~/.pyenv/versions/neovim2/bin/python -m pip install -U pip pynvim
      args:
        executable: /bin/bash
      register: pip_neovim2_script_result

    - name: pip | pyenv | neovim3 | install requirements using shell
      tags: packages,pyenv,workstation-packages,pip,neovim3
      shell: |
        # cd to project directory
        ~/.pyenv/versions/neovim3/bin/python -m pip install -U pip bandit black pylama pynvim pylint flake8 autopep8 pep8 prospector pydocstyle pyflakes isort yapf yamllint mypy
      args:
        executable: /bin/bash
      register: pip_neovim3_script_result

    - name: pip | pyenv | neovim3 | link autopep8
      tags: packages,pyenv,workstation-packages,pip,neovim3,autopep8-link
      file:
        src: ~/.pyenv/versions/neovim3/bin/autopep8
        dest: ~/bin/autopep8
        owner: barbosa
        group: barbosa
        state: link

    - name: pip | pyenv | neovim3 | link bandit
      tags: packages,pyenv,workstation-packages,pip,neovim3,bandit-link
      file:
        src: ~/.pyenv/versions/neovim3/bin/bandit
        dest: ~/bin/bandit
        owner: barbosa
        group: barbosa
        state: link

    - name: pip | pyenv | neovim3 | link black
      tags: packages,pyenv,workstation-packages,pip,neovim3,black-link
      file:
        src: ~/.pyenv/versions/neovim3/bin/black
        dest: ~/bin/black
        owner: barbosa
        group: barbosa
        state: link

    - name: pip | pyenv | neovim3 | link flake8
      tags: packages,pyenv,workstation-packages,pip,neovim3,flake8-link
      file:
        src: ~/.pyenv/versions/neovim3/bin/flake8
        dest: ~/bin/flake8
        owner: barbosa
        group: barbosa
        state: link

    - name: pip | pyenv | neovim3 | link isort
      tags: packages,pyenv,workstation-packages,pip,neovim3,isort-link
      file:
        src: ~/.pyenv/versions/neovim3/bin/isort
        dest: ~/bin/isort
        owner: barbosa
        group: barbosa
        state: link

    - name: pip | pyenv | neovim3 | link prospector
      tags: packages,pyenv,workstation-packages,pip,neovim3,prospector-link
      file:
        src: ~/.pyenv/versions/neovim3/bin/prospector
        dest: ~/bin/prospector
        owner: barbosa
        group: barbosa
        state: link

    - name: pip | pyenv | neovim3 | link pydocstyle
      tags: packages,pyenv,workstation-packages,pip,neovim3,pydocstyle-link
      file:
        src: ~/.pyenv/versions/neovim3/bin/pydocstyle
        dest: ~/bin/pydocstyle
        owner: barbosa
        group: barbosa
        state: link

    - name: pip | pyenv | neovim3 | link mypy
      tags: packages,pyenv,workstation-packages,pip,neovim3,mypy-link
      file:
        src: ~/.pyenv/versions/neovim3/bin/mypy
        dest: ~/bin/mypy
        owner: barbosa
        group: barbosa
        state: link

    - name: pip | pyenv | neovim3 | link pylama
      tags: packages,pyenv,workstation-packages,pip,neovim3,pylama-link
      file:
        src: ~/.pyenv/versions/neovim3/bin/pylama
        dest: ~/bin/pylama
        owner: barbosa
        group: barbosa
        state: link

    - name: pip | pyenv | neovim3 | link pylint
      tags: packages,pyenv,workstation-packages,pip,neovim3,pylint-link
      file:
        src: ~/.pyenv/versions/neovim3/bin/pylint
        dest: ~/bin/pylint
        owner: barbosa
        group: barbosa
        state: link

    - name: pip | pyenv | neovim3 | link yapf
      tags: packages,pyenv,workstation-packages,pip,neovim3,yapf-link
      file:
        src: ~/.pyenv/versions/neovim3/bin/yapf
        dest: ~/bin/yapf
        owner: barbosa
        group: barbosa
        state: link

    - name: pip | pyenv | neovim3 | link yamllint
      tags: packages,pyenv,workstation-packages,pip,neovim3,yamllint-link
      file:
        src: ~/.pyenv/versions/neovim3/bin/yamllint
        dest: ~/bin/yamllint
        owner: barbosa
        group: barbosa
        state: link

    - name: pip | ipython | configuration
      shell: |
        # cd to project directory
        ipython profile create
        curl -L http://hbn.link/hb-ipython-startup-script > ~/.ipython/profile_default/startup/00-venv-sitepackages.py
      args:
        executable: /bin/bash
